### ISSUE TITLE
Tests and workflows 

### ISSUE THREAD

**Issue by Nelson-Gon** [srush/streambook#4]
Hello,

I was wondering what you think of adding tests to ensure that things work as expected and also GitHub actions to check for such things as working installs, imports, or tests.

Thank you,

Nelson

**Comment by srush** [comment]
Sounds great. I normally do automated linting and pytest like this file 

https://github.com/harvardnlp/pytorch-struct/blob/master/.github/workflows/torch-struct.yml

If you want to adapt something like that I would love a PR.
