### ISSUE TITLE
Output is not shown in the browser version, instead redirected to the terminal

### ISSUE THREAD

**Issue by A-Alaa** [srush/streambook#5]
By using this Python file

```python
# First test

import os
import numpy as np

print(os.listdir())
```

the output is fed to the terminal instead of the web version.

![Screenshot_2021-04-12 01pre_EDA streambook · Streamlit](https://user-images.githubusercontent.com/5414936/114433617-efd68300-9bb9-11eb-9558-f78c2939bd90.png)

**Comment by srush** [comment]
good point. I will see what I can do.

**Comment by srush** [comment]
This should work now if you pull. Can you give it a try?

![image](https://user-images.githubusercontent.com/35882/114443222-6ca63480-9b9b-11eb-9c3b-401e14534088.png)

**Comment by A-Alaa** [comment]
> good point. I will see what I can do.

Thank you for the great tool. Let me know if you need further details if you couldn't reproduce it.

**Comment by A-Alaa** [comment]
> This should work now if you pull. Can you give it a try?
> 
> ![image](https://user-images.githubusercontent.com/35882/114443222-6ca63480-9b9b-11eb-9c3b-401e14534088.png)

It works with me now.. Thank you!
